package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1



/**
 * TBoleta generated by hbm2java
 */
public class TBoleta  implements java.io.Serializable {


     private String codigoComprobante;
     private TComprobante TComprobante;
     private int numeroBoleta;
     private String serieBoleta;

    public TBoleta() {
    }

    public TBoleta(TComprobante TComprobante, int numeroBoleta, String serieBoleta) {
       this.TComprobante = TComprobante;
       this.numeroBoleta = numeroBoleta;
       this.serieBoleta = serieBoleta;
    }
   
    public String getCodigoComprobante() {
        return this.codigoComprobante;
    }
    
    public void setCodigoComprobante(String codigoComprobante) {
        this.codigoComprobante = codigoComprobante;
    }
    public TComprobante getTComprobante() {
        return this.TComprobante;
    }
    
    public void setTComprobante(TComprobante TComprobante) {
        this.TComprobante = TComprobante;
    }
    public int getNumeroBoleta() {
        return this.numeroBoleta;
    }
    
    public void setNumeroBoleta(int numeroBoleta) {
        this.numeroBoleta = numeroBoleta;
    }
    public String getSerieBoleta() {
        return this.serieBoleta;
    }
    
    public void setSerieBoleta(String serieBoleta) {
        this.serieBoleta = serieBoleta;
    }




}


