package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1



/**
 * TCuentas generated by hbm2java
 */
public class TCuentas  implements java.io.Serializable {


     private int codigoCuenta;
     private TLocal TLocal;
     private String monedaCuenta;
     private String tipoCuenta;
     private String nombreBancoCuenta;
     private String titularCuenta;
     private String numeroCuenta;
     private String cciCuenta;
     private String descripcionCuenta;
     private boolean estadoCuenta;

    public TCuentas() {
    }

	
    public TCuentas(int codigoCuenta, TLocal TLocal, String monedaCuenta, String tipoCuenta, String nombreBancoCuenta, String titularCuenta, String numeroCuenta, boolean estadoCuenta) {
        this.codigoCuenta = codigoCuenta;
        this.TLocal = TLocal;
        this.monedaCuenta = monedaCuenta;
        this.tipoCuenta = tipoCuenta;
        this.nombreBancoCuenta = nombreBancoCuenta;
        this.titularCuenta = titularCuenta;
        this.numeroCuenta = numeroCuenta;
        this.estadoCuenta = estadoCuenta;
    }
    public TCuentas(int codigoCuenta, TLocal TLocal, String monedaCuenta, String tipoCuenta, String nombreBancoCuenta, String titularCuenta, String numeroCuenta, String cciCuenta, String descripcionCuenta, boolean estadoCuenta) {
       this.codigoCuenta = codigoCuenta;
       this.TLocal = TLocal;
       this.monedaCuenta = monedaCuenta;
       this.tipoCuenta = tipoCuenta;
       this.nombreBancoCuenta = nombreBancoCuenta;
       this.titularCuenta = titularCuenta;
       this.numeroCuenta = numeroCuenta;
       this.cciCuenta = cciCuenta;
       this.descripcionCuenta = descripcionCuenta;
       this.estadoCuenta = estadoCuenta;
    }
   
    public int getCodigoCuenta() {
        return this.codigoCuenta;
    }
    
    public void setCodigoCuenta(int codigoCuenta) {
        this.codigoCuenta = codigoCuenta;
    }
    public TLocal getTLocal() {
        return this.TLocal;
    }
    
    public void setTLocal(TLocal TLocal) {
        this.TLocal = TLocal;
    }
    public String getMonedaCuenta() {
        return this.monedaCuenta;
    }
    
    public void setMonedaCuenta(String monedaCuenta) {
        this.monedaCuenta = monedaCuenta;
    }
    public String getTipoCuenta() {
        return this.tipoCuenta;
    }
    
    public void setTipoCuenta(String tipoCuenta) {
        this.tipoCuenta = tipoCuenta;
    }
    public String getNombreBancoCuenta() {
        return this.nombreBancoCuenta;
    }
    
    public void setNombreBancoCuenta(String nombreBancoCuenta) {
        this.nombreBancoCuenta = nombreBancoCuenta;
    }
    public String getTitularCuenta() {
        return this.titularCuenta;
    }
    
    public void setTitularCuenta(String titularCuenta) {
        this.titularCuenta = titularCuenta;
    }
    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }
    public String getCciCuenta() {
        return this.cciCuenta;
    }
    
    public void setCciCuenta(String cciCuenta) {
        this.cciCuenta = cciCuenta;
    }
    public String getDescripcionCuenta() {
        return this.descripcionCuenta;
    }
    
    public void setDescripcionCuenta(String descripcionCuenta) {
        this.descripcionCuenta = descripcionCuenta;
    }
    public boolean isEstadoCuenta() {
        return this.estadoCuenta;
    }
    
    public void setEstadoCuenta(boolean estadoCuenta) {
        this.estadoCuenta = estadoCuenta;
    }




}


