package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1



/**
 * TFactura generated by hbm2java
 */
public class TFactura  implements java.io.Serializable {


     private String codigoComprobante;
     private TComprobante TComprobante;
     private int numeroFactura;
     private String serieFactura;
     private Boolean detraccionFactura;

    public TFactura() {
    }

	
    public TFactura(TComprobante TComprobante, int numeroFactura, String serieFactura) {
        this.TComprobante = TComprobante;
        this.numeroFactura = numeroFactura;
        this.serieFactura = serieFactura;
    }
    public TFactura(TComprobante TComprobante, int numeroFactura, String serieFactura, Boolean detraccionFactura) {
       this.TComprobante = TComprobante;
       this.numeroFactura = numeroFactura;
       this.serieFactura = serieFactura;
       this.detraccionFactura = detraccionFactura;
    }
   
    public String getCodigoComprobante() {
        return this.codigoComprobante;
    }
    
    public void setCodigoComprobante(String codigoComprobante) {
        this.codigoComprobante = codigoComprobante;
    }
    public TComprobante getTComprobante() {
        return this.TComprobante;
    }
    
    public void setTComprobante(TComprobante TComprobante) {
        this.TComprobante = TComprobante;
    }
    public int getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(int numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public String getSerieFactura() {
        return this.serieFactura;
    }
    
    public void setSerieFactura(String serieFactura) {
        this.serieFactura = serieFactura;
    }
    public Boolean getDetraccionFactura() {
        return this.detraccionFactura;
    }
    
    public void setDetraccionFactura(Boolean detraccionFactura) {
        this.detraccionFactura = detraccionFactura;
    }




}


