package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TIgv generated by hbm2java
 */
public class TIgv  implements java.io.Serializable {


     private int codigoIgv;
     private String tipoIgv;
     private BigDecimal porcentajeIgv;
     private Set TVentas = new HashSet(0);

    public TIgv() {
    }

	
    public TIgv(int codigoIgv, String tipoIgv, BigDecimal porcentajeIgv) {
        this.codigoIgv = codigoIgv;
        this.tipoIgv = tipoIgv;
        this.porcentajeIgv = porcentajeIgv;
    }
    public TIgv(int codigoIgv, String tipoIgv, BigDecimal porcentajeIgv, Set TVentas) {
       this.codigoIgv = codigoIgv;
       this.tipoIgv = tipoIgv;
       this.porcentajeIgv = porcentajeIgv;
       this.TVentas = TVentas;
    }
   
    public int getCodigoIgv() {
        return this.codigoIgv;
    }
    
    public void setCodigoIgv(int codigoIgv) {
        this.codigoIgv = codigoIgv;
    }
    public String getTipoIgv() {
        return this.tipoIgv;
    }
    
    public void setTipoIgv(String tipoIgv) {
        this.tipoIgv = tipoIgv;
    }
    public BigDecimal getPorcentajeIgv() {
        return this.porcentajeIgv;
    }
    
    public void setPorcentajeIgv(BigDecimal porcentajeIgv) {
        this.porcentajeIgv = porcentajeIgv;
    }
    public Set getTVentas() {
        return this.TVentas;
    }
    
    public void setTVentas(Set TVentas) {
        this.TVentas = TVentas;
    }




}


