package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TLocal generated by hbm2java
 */
public class TLocal  implements java.io.Serializable {


     private int codigoLocal;
     private String nombreLocal;
     private int ubigeoInei;
     private String departamento;
     private String provincia;
     private String distrito;
     private String direccion;
     private Set TCuentases = new HashSet(0);
     private Set TUsuariosLocals = new HashSet(0);
     private Set TSeries = new HashSet(0);
     private Set TPrincipals = new HashSet(0);

    public TLocal() {
    }

	
    public TLocal(int codigoLocal, String nombreLocal, int ubigeoInei, String departamento, String provincia, String distrito, String direccion) {
        this.codigoLocal = codigoLocal;
        this.nombreLocal = nombreLocal;
        this.ubigeoInei = ubigeoInei;
        this.departamento = departamento;
        this.provincia = provincia;
        this.distrito = distrito;
        this.direccion = direccion;
    }
    public TLocal(int codigoLocal, String nombreLocal, int ubigeoInei, String departamento, String provincia, String distrito, String direccion, Set TCuentases, Set TUsuariosLocals, Set TSeries, Set TPrincipals) {
       this.codigoLocal = codigoLocal;
       this.nombreLocal = nombreLocal;
       this.ubigeoInei = ubigeoInei;
       this.departamento = departamento;
       this.provincia = provincia;
       this.distrito = distrito;
       this.direccion = direccion;
       this.TCuentases = TCuentases;
       this.TUsuariosLocals = TUsuariosLocals;
       this.TSeries = TSeries;
       this.TPrincipals = TPrincipals;
    }
   
    public int getCodigoLocal() {
        return this.codigoLocal;
    }
    
    public void setCodigoLocal(int codigoLocal) {
        this.codigoLocal = codigoLocal;
    }
    public String getNombreLocal() {
        return this.nombreLocal;
    }
    
    public void setNombreLocal(String nombreLocal) {
        this.nombreLocal = nombreLocal;
    }
    public int getUbigeoInei() {
        return this.ubigeoInei;
    }
    
    public void setUbigeoInei(int ubigeoInei) {
        this.ubigeoInei = ubigeoInei;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getTCuentases() {
        return this.TCuentases;
    }
    
    public void setTCuentases(Set TCuentases) {
        this.TCuentases = TCuentases;
    }
    public Set getTUsuariosLocals() {
        return this.TUsuariosLocals;
    }
    
    public void setTUsuariosLocals(Set TUsuariosLocals) {
        this.TUsuariosLocals = TUsuariosLocals;
    }
    public Set getTSeries() {
        return this.TSeries;
    }
    
    public void setTSeries(Set TSeries) {
        this.TSeries = TSeries;
    }
    public Set getTPrincipals() {
        return this.TPrincipals;
    }
    
    public void setTPrincipals(Set TPrincipals) {
        this.TPrincipals = TPrincipals;
    }




}


