package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1



/**
 * TNotaCredito generated by hbm2java
 */
public class TNotaCredito  implements java.io.Serializable {


     private String codigoComprobante;
     private TComprobante TComprobante;
     private int numeroCredito;
     private String serieCredito;
     private String docModificar;
     private String serieDocModificar;
     private Integer numeroDocModificar;
     private String tipoNotaCredito;

    public TNotaCredito() {
    }

	
    public TNotaCredito(TComprobante TComprobante, int numeroCredito, String serieCredito, String docModificar, String tipoNotaCredito) {
        this.TComprobante = TComprobante;
        this.numeroCredito = numeroCredito;
        this.serieCredito = serieCredito;
        this.docModificar = docModificar;
        this.tipoNotaCredito = tipoNotaCredito;
    }
    public TNotaCredito(TComprobante TComprobante, int numeroCredito, String serieCredito, String docModificar, String serieDocModificar, Integer numeroDocModificar, String tipoNotaCredito) {
       this.TComprobante = TComprobante;
       this.numeroCredito = numeroCredito;
       this.serieCredito = serieCredito;
       this.docModificar = docModificar;
       this.serieDocModificar = serieDocModificar;
       this.numeroDocModificar = numeroDocModificar;
       this.tipoNotaCredito = tipoNotaCredito;
    }
   
    public String getCodigoComprobante() {
        return this.codigoComprobante;
    }
    
    public void setCodigoComprobante(String codigoComprobante) {
        this.codigoComprobante = codigoComprobante;
    }
    public TComprobante getTComprobante() {
        return this.TComprobante;
    }
    
    public void setTComprobante(TComprobante TComprobante) {
        this.TComprobante = TComprobante;
    }
    public int getNumeroCredito() {
        return this.numeroCredito;
    }
    
    public void setNumeroCredito(int numeroCredito) {
        this.numeroCredito = numeroCredito;
    }
    public String getSerieCredito() {
        return this.serieCredito;
    }
    
    public void setSerieCredito(String serieCredito) {
        this.serieCredito = serieCredito;
    }
    public String getDocModificar() {
        return this.docModificar;
    }
    
    public void setDocModificar(String docModificar) {
        this.docModificar = docModificar;
    }
    public String getSerieDocModificar() {
        return this.serieDocModificar;
    }
    
    public void setSerieDocModificar(String serieDocModificar) {
        this.serieDocModificar = serieDocModificar;
    }
    public Integer getNumeroDocModificar() {
        return this.numeroDocModificar;
    }
    
    public void setNumeroDocModificar(Integer numeroDocModificar) {
        this.numeroDocModificar = numeroDocModificar;
    }
    public String getTipoNotaCredito() {
        return this.tipoNotaCredito;
    }
    
    public void setTipoNotaCredito(String tipoNotaCredito) {
        this.tipoNotaCredito = tipoNotaCredito;
    }




}


