package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1



/**
 * TNotaDebito generated by hbm2java
 */
public class TNotaDebito  implements java.io.Serializable {


     private String codigoComprobante;
     private TComprobante TComprobante;
     private int numeroDebito;
     private String serieDebito;
     private String docModificar;
     private String serieDocModificar;
     private String numeroDocModificar;
     private String tipoNotaDebito;

    public TNotaDebito() {
    }

	
    public TNotaDebito(TComprobante TComprobante, int numeroDebito, String serieDebito, String tipoNotaDebito) {
        this.TComprobante = TComprobante;
        this.numeroDebito = numeroDebito;
        this.serieDebito = serieDebito;
        this.tipoNotaDebito = tipoNotaDebito;
    }
    public TNotaDebito(TComprobante TComprobante, int numeroDebito, String serieDebito, String docModificar, String serieDocModificar, String numeroDocModificar, String tipoNotaDebito) {
       this.TComprobante = TComprobante;
       this.numeroDebito = numeroDebito;
       this.serieDebito = serieDebito;
       this.docModificar = docModificar;
       this.serieDocModificar = serieDocModificar;
       this.numeroDocModificar = numeroDocModificar;
       this.tipoNotaDebito = tipoNotaDebito;
    }
   
    public String getCodigoComprobante() {
        return this.codigoComprobante;
    }
    
    public void setCodigoComprobante(String codigoComprobante) {
        this.codigoComprobante = codigoComprobante;
    }
    public TComprobante getTComprobante() {
        return this.TComprobante;
    }
    
    public void setTComprobante(TComprobante TComprobante) {
        this.TComprobante = TComprobante;
    }
    public int getNumeroDebito() {
        return this.numeroDebito;
    }
    
    public void setNumeroDebito(int numeroDebito) {
        this.numeroDebito = numeroDebito;
    }
    public String getSerieDebito() {
        return this.serieDebito;
    }
    
    public void setSerieDebito(String serieDebito) {
        this.serieDebito = serieDebito;
    }
    public String getDocModificar() {
        return this.docModificar;
    }
    
    public void setDocModificar(String docModificar) {
        this.docModificar = docModificar;
    }
    public String getSerieDocModificar() {
        return this.serieDocModificar;
    }
    
    public void setSerieDocModificar(String serieDocModificar) {
        this.serieDocModificar = serieDocModificar;
    }
    public String getNumeroDocModificar() {
        return this.numeroDocModificar;
    }
    
    public void setNumeroDocModificar(String numeroDocModificar) {
        this.numeroDocModificar = numeroDocModificar;
    }
    public String getTipoNotaDebito() {
        return this.tipoNotaDebito;
    }
    
    public void setTipoNotaDebito(String tipoNotaDebito) {
        this.tipoNotaDebito = tipoNotaDebito;
    }




}


