package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TPrincipal generated by hbm2java
 */
public class TPrincipal  implements java.io.Serializable {


     private String rucPrincipal;
     private TLocal TLocal;
     private String razonSocialPrincipal;
     private String telefonoPrincipal;
     private String emailPrincipal;
     private String razonComercialPrincipal;
     private String webPrincipal;
     private byte[] logoPrincipal;
     private String formatoFacturasPrincipal;
     private String formatoBoletasPrincipal;
     private String colorComprobantePrincipal;
     private String datosCabeceraPrincipal;
     private Set TComprobantes = new HashSet(0);

    public TPrincipal() {
    }

	
    public TPrincipal(String rucPrincipal, TLocal TLocal, String formatoFacturasPrincipal, String formatoBoletasPrincipal, String colorComprobantePrincipal, String datosCabeceraPrincipal) {
        this.rucPrincipal = rucPrincipal;
        this.TLocal = TLocal;
        this.formatoFacturasPrincipal = formatoFacturasPrincipal;
        this.formatoBoletasPrincipal = formatoBoletasPrincipal;
        this.colorComprobantePrincipal = colorComprobantePrincipal;
        this.datosCabeceraPrincipal = datosCabeceraPrincipal;
    }
    public TPrincipal(String rucPrincipal, TLocal TLocal, String razonSocialPrincipal, String telefonoPrincipal, String emailPrincipal, String razonComercialPrincipal, String webPrincipal, byte[] logoPrincipal, String formatoFacturasPrincipal, String formatoBoletasPrincipal, String colorComprobantePrincipal, String datosCabeceraPrincipal, Set TComprobantes) {
       this.rucPrincipal = rucPrincipal;
       this.TLocal = TLocal;
       this.razonSocialPrincipal = razonSocialPrincipal;
       this.telefonoPrincipal = telefonoPrincipal;
       this.emailPrincipal = emailPrincipal;
       this.razonComercialPrincipal = razonComercialPrincipal;
       this.webPrincipal = webPrincipal;
       this.logoPrincipal = logoPrincipal;
       this.formatoFacturasPrincipal = formatoFacturasPrincipal;
       this.formatoBoletasPrincipal = formatoBoletasPrincipal;
       this.colorComprobantePrincipal = colorComprobantePrincipal;
       this.datosCabeceraPrincipal = datosCabeceraPrincipal;
       this.TComprobantes = TComprobantes;
    }
   
    public String getRucPrincipal() {
        return this.rucPrincipal;
    }
    
    public void setRucPrincipal(String rucPrincipal) {
        this.rucPrincipal = rucPrincipal;
    }
    public TLocal getTLocal() {
        return this.TLocal;
    }
    
    public void setTLocal(TLocal TLocal) {
        this.TLocal = TLocal;
    }
    public String getRazonSocialPrincipal() {
        return this.razonSocialPrincipal;
    }
    
    public void setRazonSocialPrincipal(String razonSocialPrincipal) {
        this.razonSocialPrincipal = razonSocialPrincipal;
    }
    public String getTelefonoPrincipal() {
        return this.telefonoPrincipal;
    }
    
    public void setTelefonoPrincipal(String telefonoPrincipal) {
        this.telefonoPrincipal = telefonoPrincipal;
    }
    public String getEmailPrincipal() {
        return this.emailPrincipal;
    }
    
    public void setEmailPrincipal(String emailPrincipal) {
        this.emailPrincipal = emailPrincipal;
    }
    public String getRazonComercialPrincipal() {
        return this.razonComercialPrincipal;
    }
    
    public void setRazonComercialPrincipal(String razonComercialPrincipal) {
        this.razonComercialPrincipal = razonComercialPrincipal;
    }
    public String getWebPrincipal() {
        return this.webPrincipal;
    }
    
    public void setWebPrincipal(String webPrincipal) {
        this.webPrincipal = webPrincipal;
    }
    public byte[] getLogoPrincipal() {
        return this.logoPrincipal;
    }
    
    public void setLogoPrincipal(byte[] logoPrincipal) {
        this.logoPrincipal = logoPrincipal;
    }
    public String getFormatoFacturasPrincipal() {
        return this.formatoFacturasPrincipal;
    }
    
    public void setFormatoFacturasPrincipal(String formatoFacturasPrincipal) {
        this.formatoFacturasPrincipal = formatoFacturasPrincipal;
    }
    public String getFormatoBoletasPrincipal() {
        return this.formatoBoletasPrincipal;
    }
    
    public void setFormatoBoletasPrincipal(String formatoBoletasPrincipal) {
        this.formatoBoletasPrincipal = formatoBoletasPrincipal;
    }
    public String getColorComprobantePrincipal() {
        return this.colorComprobantePrincipal;
    }
    
    public void setColorComprobantePrincipal(String colorComprobantePrincipal) {
        this.colorComprobantePrincipal = colorComprobantePrincipal;
    }
    public String getDatosCabeceraPrincipal() {
        return this.datosCabeceraPrincipal;
    }
    
    public void setDatosCabeceraPrincipal(String datosCabeceraPrincipal) {
        this.datosCabeceraPrincipal = datosCabeceraPrincipal;
    }
    public Set getTComprobantes() {
        return this.TComprobantes;
    }
    
    public void setTComprobantes(Set TComprobantes) {
        this.TComprobantes = TComprobantes;
    }




}


