package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TProducto generated by hbm2java
 */
public class TProducto  implements java.io.Serializable {


     private String codigoProducto;
     private TUnidadMedida TUnidadMedida;
     private String nombreProducto;
     private String monedaProducto;
     private BigDecimal valorUProducto;
     private BigDecimal precioUProducto;
     private Set TVentas = new HashSet(0);

    public TProducto() {
    }

	
    public TProducto(String codigoProducto, TUnidadMedida TUnidadMedida, String nombreProducto, String monedaProducto) {
        this.codigoProducto = codigoProducto;
        this.TUnidadMedida = TUnidadMedida;
        this.nombreProducto = nombreProducto;
        this.monedaProducto = monedaProducto;
    }
    public TProducto(String codigoProducto, TUnidadMedida TUnidadMedida, String nombreProducto, String monedaProducto, BigDecimal valorUProducto, BigDecimal precioUProducto, Set TVentas) {
       this.codigoProducto = codigoProducto;
       this.TUnidadMedida = TUnidadMedida;
       this.nombreProducto = nombreProducto;
       this.monedaProducto = monedaProducto;
       this.valorUProducto = valorUProducto;
       this.precioUProducto = precioUProducto;
       this.TVentas = TVentas;
    }
   
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public TUnidadMedida getTUnidadMedida() {
        return this.TUnidadMedida;
    }
    
    public void setTUnidadMedida(TUnidadMedida TUnidadMedida) {
        this.TUnidadMedida = TUnidadMedida;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public String getMonedaProducto() {
        return this.monedaProducto;
    }
    
    public void setMonedaProducto(String monedaProducto) {
        this.monedaProducto = monedaProducto;
    }
    public BigDecimal getValorUProducto() {
        return this.valorUProducto;
    }
    
    public void setValorUProducto(BigDecimal valorUProducto) {
        this.valorUProducto = valorUProducto;
    }
    public BigDecimal getPrecioUProducto() {
        return this.precioUProducto;
    }
    
    public void setPrecioUProducto(BigDecimal precioUProducto) {
        this.precioUProducto = precioUProducto;
    }
    public Set getTVentas() {
        return this.TVentas;
    }
    
    public void setTVentas(Set TVentas) {
        this.TVentas = TVentas;
    }




}


