package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TUnidadMedida generated by hbm2java
 */
public class TUnidadMedida  implements java.io.Serializable {


     private String codigoTipo;
     private TTipoUnidad TTipoUnidad;
     private String descripcionUnidad;
     private Set TProductos = new HashSet(0);

    public TUnidadMedida() {
    }

	
    public TUnidadMedida(TTipoUnidad TTipoUnidad, String descripcionUnidad) {
        this.TTipoUnidad = TTipoUnidad;
        this.descripcionUnidad = descripcionUnidad;
    }
    public TUnidadMedida(TTipoUnidad TTipoUnidad, String descripcionUnidad, Set TProductos) {
       this.TTipoUnidad = TTipoUnidad;
       this.descripcionUnidad = descripcionUnidad;
       this.TProductos = TProductos;
    }
   
    public String getCodigoTipo() {
        return this.codigoTipo;
    }
    
    public void setCodigoTipo(String codigoTipo) {
        this.codigoTipo = codigoTipo;
    }
    public TTipoUnidad getTTipoUnidad() {
        return this.TTipoUnidad;
    }
    
    public void setTTipoUnidad(TTipoUnidad TTipoUnidad) {
        this.TTipoUnidad = TTipoUnidad;
    }
    public String getDescripcionUnidad() {
        return this.descripcionUnidad;
    }
    
    public void setDescripcionUnidad(String descripcionUnidad) {
        this.descripcionUnidad = descripcionUnidad;
    }
    public Set getTProductos() {
        return this.TProductos;
    }
    
    public void setTProductos(Set TProductos) {
        this.TProductos = TProductos;
    }




}


