package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1



/**
 * TUsuariosLocal generated by hbm2java
 */
public class TUsuariosLocal  implements java.io.Serializable {


     private int iduserlocal;
     private TLocal TLocal;
     private TUsuario TUsuario;

    public TUsuariosLocal() {
    }

    public TUsuariosLocal(int iduserlocal, TLocal TLocal, TUsuario TUsuario) {
       this.iduserlocal = iduserlocal;
       this.TLocal = TLocal;
       this.TUsuario = TUsuario;
    }
   
    public int getIduserlocal() {
        return this.iduserlocal;
    }
    
    public void setIduserlocal(int iduserlocal) {
        this.iduserlocal = iduserlocal;
    }
    public TLocal getTLocal() {
        return this.TLocal;
    }
    
    public void setTLocal(TLocal TLocal) {
        this.TLocal = TLocal;
    }
    public TUsuario getTUsuario() {
        return this.TUsuario;
    }
    
    public void setTUsuario(TUsuario TUsuario) {
        this.TUsuario = TUsuario;
    }




}


