package com.incomab.model;
// Generated 29/08/2017 10:56:47 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TVenta generated by hbm2java
 */
public class TVenta  implements java.io.Serializable {


     private int idVenta;
     private TComprobante TComprobante;
     private TIgv TIgv;
     private TProducto TProducto;
     private String detalleAdicionalVenta;
     private int cantidadVenta;
     private BigDecimal valorUVenta;
     private BigDecimal subtotalVenta;
     private BigDecimal totalVenta;

    public TVenta() {
    }

	
    public TVenta(int idVenta, TComprobante TComprobante, TIgv TIgv, TProducto TProducto, int cantidadVenta, BigDecimal valorUVenta, BigDecimal subtotalVenta, BigDecimal totalVenta) {
        this.idVenta = idVenta;
        this.TComprobante = TComprobante;
        this.TIgv = TIgv;
        this.TProducto = TProducto;
        this.cantidadVenta = cantidadVenta;
        this.valorUVenta = valorUVenta;
        this.subtotalVenta = subtotalVenta;
        this.totalVenta = totalVenta;
    }
    public TVenta(int idVenta, TComprobante TComprobante, TIgv TIgv, TProducto TProducto, String detalleAdicionalVenta, int cantidadVenta, BigDecimal valorUVenta, BigDecimal subtotalVenta, BigDecimal totalVenta) {
       this.idVenta = idVenta;
       this.TComprobante = TComprobante;
       this.TIgv = TIgv;
       this.TProducto = TProducto;
       this.detalleAdicionalVenta = detalleAdicionalVenta;
       this.cantidadVenta = cantidadVenta;
       this.valorUVenta = valorUVenta;
       this.subtotalVenta = subtotalVenta;
       this.totalVenta = totalVenta;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public TComprobante getTComprobante() {
        return this.TComprobante;
    }
    
    public void setTComprobante(TComprobante TComprobante) {
        this.TComprobante = TComprobante;
    }
    public TIgv getTIgv() {
        return this.TIgv;
    }
    
    public void setTIgv(TIgv TIgv) {
        this.TIgv = TIgv;
    }
    public TProducto getTProducto() {
        return this.TProducto;
    }
    
    public void setTProducto(TProducto TProducto) {
        this.TProducto = TProducto;
    }
    public String getDetalleAdicionalVenta() {
        return this.detalleAdicionalVenta;
    }
    
    public void setDetalleAdicionalVenta(String detalleAdicionalVenta) {
        this.detalleAdicionalVenta = detalleAdicionalVenta;
    }
    public int getCantidadVenta() {
        return this.cantidadVenta;
    }
    
    public void setCantidadVenta(int cantidadVenta) {
        this.cantidadVenta = cantidadVenta;
    }
    public BigDecimal getValorUVenta() {
        return this.valorUVenta;
    }
    
    public void setValorUVenta(BigDecimal valorUVenta) {
        this.valorUVenta = valorUVenta;
    }
    public BigDecimal getSubtotalVenta() {
        return this.subtotalVenta;
    }
    
    public void setSubtotalVenta(BigDecimal subtotalVenta) {
        this.subtotalVenta = subtotalVenta;
    }
    public BigDecimal getTotalVenta() {
        return this.totalVenta;
    }
    
    public void setTotalVenta(BigDecimal totalVenta) {
        this.totalVenta = totalVenta;
    }




}


